//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping
{


    public partial class SelectScreening
    {

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblMovieTitle;

        protected global::System.Web.UI.WebControls.Panel pnlScreeningsByDate;

        protected global::System.Web.UI.WebControls.Repeater rptDays;

        protected global::System.Web.UI.WebControls.Label lblNoScreenings;
    }
}
